name: gml
dependencies:
  - python==3.8.*
  - conda==4.12.*
  - pip==21.2.*
  - pip:
      - networkx==2.8
      - snap-stanford==6.0.0
      - matplotlib==3.5.1
      - pandas==1.3.5
      - scipy==1.8.0
      - jupyter==1.0.0
      - numpy==1.22.3
      - python-Levenshtein==0.12.2
      - node2vec==0.4.5
      - karateclub==1.2.3
      - stellargraph==1.2.1
      - chardet==4.0.0
      - psutil==5.9.1
